# Generated by Django 6.0.5 on 2026-05-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='tip_type',
            field=models.CharField(choices=[('general', 'General'), ('food', 'Food'), ('views', 'Views'), ('attractions', 'Attractions'), ('sightseeing', 'Sightseeing'), ('outdoors', 'Outdoors')], max_length=100),
        ),
    ]
