# Generated by Django 6.0.5 on 2026-05-09 21:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_tip_approved_tip_user_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
